# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push, workflow_call]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Set Mod variables
        run: |
          echo "VERSION=$(./gradlew properties | grep '^version:' | awk '{print $NF}' )" >> $GITHUB_ENV
          echo "NAME=$(./gradlew properties | grep '^archives_base_name:' | awk '{print $NF}' )" >> $GITHUB_ENV
          
      - name: build
        run: ./gradlew build

      - name: Test
        run: ls build/libs
      - name: Test
        run: echo build/libs/${NAME}-${VERSION}-sources.jar
        
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs/${NAME}-${VERSION}.jar
      - name: Upload build sources
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs/${NAME}-${VERSION}-sources.jar
