# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish
on: workflow_dispatch

jobs:
  build:
    uses: JulianWww/GeckoBoyArrowTweaks/.github/workflows/build.yml@main
    
  publish:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Set Mod variables
        run: |
          echo "VERSION=$(cat gradle.properties | grep ^mod_version= | cut -c 13-)" >> $GITHUB_ENV
          echo "NAME=$(cat gradle.properties | grep ^archives_base_name= | cut -c 20-)" >> $GITHUB_ENV
          echo "MC_VERSION=$(cat gradle.properties | grep ^minecraft_version= | cut -c 19-)" >> $GITHUB_ENV
          echo "CHANNEL=$(echo $VERSION | sed "s/^[0-9]/release/" | tr -d -c [a-z])" >> $GITHUB_ENV
          
      - uses: actions/download-artifact@v5
        with:
          name: mod
      - name: Rename build file
        run: mv ${{ env.NAME }}-${{ env.VERSION }}.jar ${{ env.NAME }}-${{ env.VERSION }}+mc${{ env.MC_VERSION }}.jar      

      - uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: AXlv9DZi
          version: ${{ env.VERSION }}
          loaders: fabric
          game-versions: ${{ env.MC_VERSION }}
          files: ${{ env.NAME }}-${{ env.VERSION }}+mc${{ env.MC_VERSION }}.jar
          channel: $CHANNEL
