# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: publish
on: workflow_dispatch

jobs:
  build:
    uses: JulianWww/GeckoBoyArrowTweaks/.github/workflows/build.yml@v1
    
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Set Mod variables
        run: |
          echo "VERSION=$(cat gradle.properties | grep ^mod_version= | cut -c 13-)" >> $GITHUB_ENV
          echo "NAME=$(cat gradle.properties | grep ^archives_base_name= | cut -c 20-)" >> $GITHUB_ENV
          
      - uses: actions/download-artifact@v5
        with:
          name: mod
      - name: Display structure of downloaded files
        run: ls -R
